import type { VisitedMapCountryCode } from "@/registry/visited-map/visited-map"

/**
 * UN geoscheme regions, with the Americas split into North America, Central
 * America & Caribbean, and South America.
 */
export type Continent =
  | "Africa"
  | "Asia"
  | "Europe"
  | "North America"
  | "Central America & Caribbean"
  | "South America"
  | "Oceania"
  | "Antarctica"

export type Region = {
  /** ISO 3166-1 alpha-2 code ("XK" for Kosovo), usable in VisitedMap's `countries`. */
  code: VisitedMapCountryCode
  name: string
}

/** Regions grouped by continent, in display order. */
export type RegionGroups = Partial<Record<Continent, Region[]>>

// The 195 countries counted by getVisitedStats: UN member states plus the
// Vatican and Palestine. English short names from mledoze/countries (ODbL).
export const countries = {
  Africa: [
    { code: "DZ", name: "Algeria" },
    { code: "AO", name: "Angola" },
    { code: "BJ", name: "Benin" },
    { code: "BW", name: "Botswana" },
    { code: "BF", name: "Burkina Faso" },
    { code: "BI", name: "Burundi" },
    { code: "CM", name: "Cameroon" },
    { code: "CV", name: "Cape Verde" },
    { code: "CF", name: "Central African Republic" },
    { code: "TD", name: "Chad" },
    { code: "KM", name: "Comoros" },
    { code: "CG", name: "Congo" },
    { code: "DJ", name: "Djibouti" },
    { code: "CD", name: "DR Congo" },
    { code: "EG", name: "Egypt" },
    { code: "GQ", name: "Equatorial Guinea" },
    { code: "ER", name: "Eritrea" },
    { code: "SZ", name: "Eswatini" },
    { code: "ET", name: "Ethiopia" },
    { code: "GA", name: "Gabon" },
    { code: "GM", name: "Gambia" },
    { code: "GH", name: "Ghana" },
    { code: "GN", name: "Guinea" },
    { code: "GW", name: "Guinea-Bissau" },
    { code: "CI", name: "Ivory Coast" },
    { code: "KE", name: "Kenya" },
    { code: "LS", name: "Lesotho" },
    { code: "LR", name: "Liberia" },
    { code: "LY", name: "Libya" },
    { code: "MG", name: "Madagascar" },
    { code: "MW", name: "Malawi" },
    { code: "ML", name: "Mali" },
    { code: "MR", name: "Mauritania" },
    { code: "MU", name: "Mauritius" },
    { code: "MA", name: "Morocco" },
    { code: "MZ", name: "Mozambique" },
    { code: "NA", name: "Namibia" },
    { code: "NE", name: "Niger" },
    { code: "NG", name: "Nigeria" },
    { code: "RW", name: "Rwanda" },
    { code: "ST", name: "São Tomé and Príncipe" },
    { code: "SN", name: "Senegal" },
    { code: "SC", name: "Seychelles" },
    { code: "SL", name: "Sierra Leone" },
    { code: "SO", name: "Somalia" },
    { code: "ZA", name: "South Africa" },
    { code: "SS", name: "South Sudan" },
    { code: "SD", name: "Sudan" },
    { code: "TZ", name: "Tanzania" },
    { code: "TG", name: "Togo" },
    { code: "TN", name: "Tunisia" },
    { code: "UG", name: "Uganda" },
    { code: "ZM", name: "Zambia" },
    { code: "ZW", name: "Zimbabwe" },
  ],
  Asia: [
    { code: "AF", name: "Afghanistan" },
    { code: "AM", name: "Armenia" },
    { code: "AZ", name: "Azerbaijan" },
    { code: "BH", name: "Bahrain" },
    { code: "BD", name: "Bangladesh" },
    { code: "BT", name: "Bhutan" },
    { code: "BN", name: "Brunei" },
    { code: "KH", name: "Cambodia" },
    { code: "CN", name: "China" },
    { code: "GE", name: "Georgia" },
    { code: "IN", name: "India" },
    { code: "ID", name: "Indonesia" },
    { code: "IR", name: "Iran" },
    { code: "IQ", name: "Iraq" },
    { code: "IL", name: "Israel" },
    { code: "JP", name: "Japan" },
    { code: "JO", name: "Jordan" },
    { code: "KZ", name: "Kazakhstan" },
    { code: "KW", name: "Kuwait" },
    { code: "KG", name: "Kyrgyzstan" },
    { code: "LA", name: "Laos" },
    { code: "LB", name: "Lebanon" },
    { code: "MY", name: "Malaysia" },
    { code: "MV", name: "Maldives" },
    { code: "MN", name: "Mongolia" },
    { code: "MM", name: "Myanmar" },
    { code: "NP", name: "Nepal" },
    { code: "KP", name: "North Korea" },
    { code: "OM", name: "Oman" },
    { code: "PK", name: "Pakistan" },
    { code: "PS", name: "Palestine" },
    { code: "PH", name: "Philippines" },
    { code: "QA", name: "Qatar" },
    { code: "SA", name: "Saudi Arabia" },
    { code: "SG", name: "Singapore" },
    { code: "KR", name: "South Korea" },
    { code: "LK", name: "Sri Lanka" },
    { code: "SY", name: "Syria" },
    { code: "TJ", name: "Tajikistan" },
    { code: "TH", name: "Thailand" },
    { code: "TL", name: "Timor-Leste" },
    { code: "TR", name: "Türkiye" },
    { code: "TM", name: "Turkmenistan" },
    { code: "AE", name: "United Arab Emirates" },
    { code: "UZ", name: "Uzbekistan" },
    { code: "VN", name: "Vietnam" },
    { code: "YE", name: "Yemen" },
  ],
  Europe: [
    { code: "AL", name: "Albania" },
    { code: "AD", name: "Andorra" },
    { code: "AT", name: "Austria" },
    { code: "BY", name: "Belarus" },
    { code: "BE", name: "Belgium" },
    { code: "BA", name: "Bosnia and Herzegovina" },
    { code: "BG", name: "Bulgaria" },
    { code: "HR", name: "Croatia" },
    { code: "CY", name: "Cyprus" },
    { code: "CZ", name: "Czechia" },
    { code: "DK", name: "Denmark" },
    { code: "EE", name: "Estonia" },
    { code: "FI", name: "Finland" },
    { code: "FR", name: "France" },
    { code: "DE", name: "Germany" },
    { code: "GR", name: "Greece" },
    { code: "HU", name: "Hungary" },
    { code: "IS", name: "Iceland" },
    { code: "IE", name: "Ireland" },
    { code: "IT", name: "Italy" },
    { code: "LV", name: "Latvia" },
    { code: "LI", name: "Liechtenstein" },
    { code: "LT", name: "Lithuania" },
    { code: "LU", name: "Luxembourg" },
    { code: "MT", name: "Malta" },
    { code: "MD", name: "Moldova" },
    { code: "MC", name: "Monaco" },
    { code: "ME", name: "Montenegro" },
    { code: "NL", name: "Netherlands" },
    { code: "MK", name: "North Macedonia" },
    { code: "NO", name: "Norway" },
    { code: "PL", name: "Poland" },
    { code: "PT", name: "Portugal" },
    { code: "RO", name: "Romania" },
    { code: "RU", name: "Russia" },
    { code: "SM", name: "San Marino" },
    { code: "RS", name: "Serbia" },
    { code: "SK", name: "Slovakia" },
    { code: "SI", name: "Slovenia" },
    { code: "ES", name: "Spain" },
    { code: "SE", name: "Sweden" },
    { code: "CH", name: "Switzerland" },
    { code: "UA", name: "Ukraine" },
    { code: "GB", name: "United Kingdom" },
    { code: "VA", name: "Vatican City" },
  ],
  "North America": [
    { code: "CA", name: "Canada" },
    { code: "MX", name: "Mexico" },
    { code: "US", name: "United States" },
  ],
  "Central America & Caribbean": [
    { code: "AG", name: "Antigua and Barbuda" },
    { code: "BS", name: "Bahamas" },
    { code: "BB", name: "Barbados" },
    { code: "BZ", name: "Belize" },
    { code: "CR", name: "Costa Rica" },
    { code: "CU", name: "Cuba" },
    { code: "DM", name: "Dominica" },
    { code: "DO", name: "Dominican Republic" },
    { code: "SV", name: "El Salvador" },
    { code: "GD", name: "Grenada" },
    { code: "GT", name: "Guatemala" },
    { code: "HT", name: "Haiti" },
    { code: "HN", name: "Honduras" },
    { code: "JM", name: "Jamaica" },
    { code: "NI", name: "Nicaragua" },
    { code: "PA", name: "Panama" },
    { code: "KN", name: "Saint Kitts and Nevis" },
    { code: "LC", name: "Saint Lucia" },
    { code: "VC", name: "Saint Vincent and the Grenadines" },
    { code: "TT", name: "Trinidad and Tobago" },
  ],
  "South America": [
    { code: "AR", name: "Argentina" },
    { code: "BO", name: "Bolivia" },
    { code: "BR", name: "Brazil" },
    { code: "CL", name: "Chile" },
    { code: "CO", name: "Colombia" },
    { code: "EC", name: "Ecuador" },
    { code: "GY", name: "Guyana" },
    { code: "PY", name: "Paraguay" },
    { code: "PE", name: "Peru" },
    { code: "SR", name: "Suriname" },
    { code: "UY", name: "Uruguay" },
    { code: "VE", name: "Venezuela" },
  ],
  Oceania: [
    { code: "AU", name: "Australia" },
    { code: "FJ", name: "Fiji" },
    { code: "KI", name: "Kiribati" },
    { code: "MH", name: "Marshall Islands" },
    { code: "FM", name: "Micronesia" },
    { code: "NR", name: "Nauru" },
    { code: "NZ", name: "New Zealand" },
    { code: "PW", name: "Palau" },
    { code: "PG", name: "Papua New Guinea" },
    { code: "WS", name: "Samoa" },
    { code: "SB", name: "Solomon Islands" },
    { code: "TO", name: "Tonga" },
    { code: "TV", name: "Tuvalu" },
    { code: "VU", name: "Vanuatu" },
  ],
} satisfies RegionGroups

// Places outside the 195: dependent territories plus Kosovo, Taiwan and Western
// Sahara. Never counted in the stats; the ones drawn on the map can still be
// highlighted, the rest show just a pin. Uninhabited ones (Antarctica, Bouvet
// Island…) are left out.
export const territories = {
  Africa: [
    { code: "IO", name: "British Indian Ocean Territory" },
    { code: "YT", name: "Mayotte" },
    { code: "RE", name: "Réunion" },
    { code: "SH", name: "Saint Helena, Ascension and Tristan da Cunha" },
    { code: "EH", name: "Western Sahara" },
  ],
  Asia: [
    { code: "HK", name: "Hong Kong" },
    { code: "MO", name: "Macau" },
    { code: "TW", name: "Taiwan" },
  ],
  Europe: [
    { code: "AX", name: "Åland Islands" },
    { code: "FO", name: "Faroe Islands" },
    { code: "GI", name: "Gibraltar" },
    { code: "GG", name: "Guernsey" },
    { code: "IM", name: "Isle of Man" },
    { code: "JE", name: "Jersey" },
    { code: "XK", name: "Kosovo" },
    { code: "SJ", name: "Svalbard and Jan Mayen" },
  ],
  "North America": [
    { code: "BM", name: "Bermuda" },
    { code: "GL", name: "Greenland" },
    { code: "PM", name: "Saint Pierre and Miquelon" },
  ],
  "Central America & Caribbean": [
    { code: "AI", name: "Anguilla" },
    { code: "AW", name: "Aruba" },
    { code: "VG", name: "British Virgin Islands" },
    { code: "BQ", name: "Caribbean Netherlands" },
    { code: "KY", name: "Cayman Islands" },
    { code: "CW", name: "Curaçao" },
    { code: "GP", name: "Guadeloupe" },
    { code: "MQ", name: "Martinique" },
    { code: "MS", name: "Montserrat" },
    { code: "PR", name: "Puerto Rico" },
    { code: "BL", name: "Saint Barthélemy" },
    { code: "MF", name: "Saint Martin" },
    { code: "SX", name: "Sint Maarten" },
    { code: "TC", name: "Turks and Caicos Islands" },
    { code: "VI", name: "United States Virgin Islands" },
  ],
  "South America": [
    { code: "FK", name: "Falkland Islands" },
    { code: "GF", name: "French Guiana" },
  ],
  Oceania: [
    { code: "AS", name: "American Samoa" },
    { code: "CX", name: "Christmas Island" },
    { code: "CC", name: "Cocos (Keeling) Islands" },
    { code: "CK", name: "Cook Islands" },
    { code: "PF", name: "French Polynesia" },
    { code: "GU", name: "Guam" },
    { code: "NC", name: "New Caledonia" },
    { code: "NU", name: "Niue" },
    { code: "NF", name: "Norfolk Island" },
    { code: "MP", name: "Northern Mariana Islands" },
    { code: "PN", name: "Pitcairn Islands" },
    { code: "TK", name: "Tokelau" },
    { code: "WF", name: "Wallis and Futuna" },
  ],
  Antarctica: [
    { code: "TF", name: "French Southern and Antarctic Lands" },
    { code: "GS", name: "South Georgia" },
  ],
} satisfies RegionGroups

/** Every region of a group, as one list. */
export function flattenRegions(groups: RegionGroups): Region[] {
  return Object.values(groups).flat()
}
