import type { VisitedMapCountryCode } from "@/registry/visited-map/visited-map"

export const continents = [
  "Africa",
  "Asia",
  "Europe",
  "North America",
  "South America",
  "Oceania",
  "Antarctica",
] as const

export type Continent = (typeof continents)[number]

export type Region = {
  /** ISO 3166-1 alpha-2 code ("XK" for Kosovo). */
  code: string
  name: string
  /**
   * UN geoscheme region, with the Americas split in two (Central America and
   * the Caribbean go with North America).
   */
  continent: Continent
  /**
   * Set when the region can be highlighted on the map or counted in
   * getVisitedStats. Territories not drawn on the map leave it out.
   */
  country?: VisitedMapCountryCode
}

// The 195 countries counted by getVisitedStats: UN member states plus the
// Vatican and Palestine. English short names from mledoze/countries (ODbL).
// prettier-ignore
export const countries: Region[] = [
  { code: "AF", name: "Afghanistan", continent: "Asia", country: "AF" },
  { code: "AL", name: "Albania", continent: "Europe", country: "AL" },
  { code: "DZ", name: "Algeria", continent: "Africa", country: "DZ" },
  { code: "AD", name: "Andorra", continent: "Europe", country: "AD" },
  { code: "AO", name: "Angola", continent: "Africa", country: "AO" },
  { code: "AG", name: "Antigua and Barbuda", continent: "North America", country: "AG" },
  { code: "AR", name: "Argentina", continent: "South America", country: "AR" },
  { code: "AM", name: "Armenia", continent: "Asia", country: "AM" },
  { code: "AU", name: "Australia", continent: "Oceania", country: "AU" },
  { code: "AT", name: "Austria", continent: "Europe", country: "AT" },
  { code: "AZ", name: "Azerbaijan", continent: "Asia", country: "AZ" },
  { code: "BS", name: "Bahamas", continent: "North America", country: "BS" },
  { code: "BH", name: "Bahrain", continent: "Asia", country: "BH" },
  { code: "BD", name: "Bangladesh", continent: "Asia", country: "BD" },
  { code: "BB", name: "Barbados", continent: "North America", country: "BB" },
  { code: "BY", name: "Belarus", continent: "Europe", country: "BY" },
  { code: "BE", name: "Belgium", continent: "Europe", country: "BE" },
  { code: "BZ", name: "Belize", continent: "North America", country: "BZ" },
  { code: "BJ", name: "Benin", continent: "Africa", country: "BJ" },
  { code: "BT", name: "Bhutan", continent: "Asia", country: "BT" },
  { code: "BO", name: "Bolivia", continent: "South America", country: "BO" },
  { code: "BA", name: "Bosnia and Herzegovina", continent: "Europe", country: "BA" },
  { code: "BW", name: "Botswana", continent: "Africa", country: "BW" },
  { code: "BR", name: "Brazil", continent: "South America", country: "BR" },
  { code: "BN", name: "Brunei", continent: "Asia", country: "BN" },
  { code: "BG", name: "Bulgaria", continent: "Europe", country: "BG" },
  { code: "BF", name: "Burkina Faso", continent: "Africa", country: "BF" },
  { code: "BI", name: "Burundi", continent: "Africa", country: "BI" },
  { code: "KH", name: "Cambodia", continent: "Asia", country: "KH" },
  { code: "CM", name: "Cameroon", continent: "Africa", country: "CM" },
  { code: "CA", name: "Canada", continent: "North America", country: "CA" },
  { code: "CV", name: "Cape Verde", continent: "Africa", country: "CV" },
  { code: "CF", name: "Central African Republic", continent: "Africa", country: "CF" },
  { code: "TD", name: "Chad", continent: "Africa", country: "TD" },
  { code: "CL", name: "Chile", continent: "South America", country: "CL" },
  { code: "CN", name: "China", continent: "Asia", country: "CN" },
  { code: "CO", name: "Colombia", continent: "South America", country: "CO" },
  { code: "KM", name: "Comoros", continent: "Africa", country: "KM" },
  { code: "CG", name: "Congo", continent: "Africa", country: "CG" },
  { code: "CR", name: "Costa Rica", continent: "North America", country: "CR" },
  { code: "HR", name: "Croatia", continent: "Europe", country: "HR" },
  { code: "CU", name: "Cuba", continent: "North America", country: "CU" },
  { code: "CY", name: "Cyprus", continent: "Europe", country: "CY" },
  { code: "CZ", name: "Czechia", continent: "Europe", country: "CZ" },
  { code: "DK", name: "Denmark", continent: "Europe", country: "DK" },
  { code: "DJ", name: "Djibouti", continent: "Africa", country: "DJ" },
  { code: "DM", name: "Dominica", continent: "North America", country: "DM" },
  { code: "DO", name: "Dominican Republic", continent: "North America", country: "DO" },
  { code: "CD", name: "DR Congo", continent: "Africa", country: "CD" },
  { code: "EC", name: "Ecuador", continent: "South America", country: "EC" },
  { code: "EG", name: "Egypt", continent: "Africa", country: "EG" },
  { code: "SV", name: "El Salvador", continent: "North America", country: "SV" },
  { code: "GQ", name: "Equatorial Guinea", continent: "Africa", country: "GQ" },
  { code: "ER", name: "Eritrea", continent: "Africa", country: "ER" },
  { code: "EE", name: "Estonia", continent: "Europe", country: "EE" },
  { code: "SZ", name: "Eswatini", continent: "Africa", country: "SZ" },
  { code: "ET", name: "Ethiopia", continent: "Africa", country: "ET" },
  { code: "FJ", name: "Fiji", continent: "Oceania", country: "FJ" },
  { code: "FI", name: "Finland", continent: "Europe", country: "FI" },
  { code: "FR", name: "France", continent: "Europe", country: "FR" },
  { code: "GA", name: "Gabon", continent: "Africa", country: "GA" },
  { code: "GM", name: "Gambia", continent: "Africa", country: "GM" },
  { code: "GE", name: "Georgia", continent: "Asia", country: "GE" },
  { code: "DE", name: "Germany", continent: "Europe", country: "DE" },
  { code: "GH", name: "Ghana", continent: "Africa", country: "GH" },
  { code: "GR", name: "Greece", continent: "Europe", country: "GR" },
  { code: "GD", name: "Grenada", continent: "North America", country: "GD" },
  { code: "GT", name: "Guatemala", continent: "North America", country: "GT" },
  { code: "GN", name: "Guinea", continent: "Africa", country: "GN" },
  { code: "GW", name: "Guinea-Bissau", continent: "Africa", country: "GW" },
  { code: "GY", name: "Guyana", continent: "South America", country: "GY" },
  { code: "HT", name: "Haiti", continent: "North America", country: "HT" },
  { code: "HN", name: "Honduras", continent: "North America", country: "HN" },
  { code: "HU", name: "Hungary", continent: "Europe", country: "HU" },
  { code: "IS", name: "Iceland", continent: "Europe", country: "IS" },
  { code: "IN", name: "India", continent: "Asia", country: "IN" },
  { code: "ID", name: "Indonesia", continent: "Asia", country: "ID" },
  { code: "IR", name: "Iran", continent: "Asia", country: "IR" },
  { code: "IQ", name: "Iraq", continent: "Asia", country: "IQ" },
  { code: "IE", name: "Ireland", continent: "Europe", country: "IE" },
  { code: "IL", name: "Israel", continent: "Asia", country: "IL" },
  { code: "IT", name: "Italy", continent: "Europe", country: "IT" },
  { code: "CI", name: "Ivory Coast", continent: "Africa", country: "CI" },
  { code: "JM", name: "Jamaica", continent: "North America", country: "JM" },
  { code: "JP", name: "Japan", continent: "Asia", country: "JP" },
  { code: "JO", name: "Jordan", continent: "Asia", country: "JO" },
  { code: "KZ", name: "Kazakhstan", continent: "Asia", country: "KZ" },
  { code: "KE", name: "Kenya", continent: "Africa", country: "KE" },
  { code: "KI", name: "Kiribati", continent: "Oceania", country: "KI" },
  { code: "KW", name: "Kuwait", continent: "Asia", country: "KW" },
  { code: "KG", name: "Kyrgyzstan", continent: "Asia", country: "KG" },
  { code: "LA", name: "Laos", continent: "Asia", country: "LA" },
  { code: "LV", name: "Latvia", continent: "Europe", country: "LV" },
  { code: "LB", name: "Lebanon", continent: "Asia", country: "LB" },
  { code: "LS", name: "Lesotho", continent: "Africa", country: "LS" },
  { code: "LR", name: "Liberia", continent: "Africa", country: "LR" },
  { code: "LY", name: "Libya", continent: "Africa", country: "LY" },
  { code: "LI", name: "Liechtenstein", continent: "Europe", country: "LI" },
  { code: "LT", name: "Lithuania", continent: "Europe", country: "LT" },
  { code: "LU", name: "Luxembourg", continent: "Europe", country: "LU" },
  { code: "MG", name: "Madagascar", continent: "Africa", country: "MG" },
  { code: "MW", name: "Malawi", continent: "Africa", country: "MW" },
  { code: "MY", name: "Malaysia", continent: "Asia", country: "MY" },
  { code: "MV", name: "Maldives", continent: "Asia", country: "MV" },
  { code: "ML", name: "Mali", continent: "Africa", country: "ML" },
  { code: "MT", name: "Malta", continent: "Europe", country: "MT" },
  { code: "MH", name: "Marshall Islands", continent: "Oceania", country: "MH" },
  { code: "MR", name: "Mauritania", continent: "Africa", country: "MR" },
  { code: "MU", name: "Mauritius", continent: "Africa", country: "MU" },
  { code: "MX", name: "Mexico", continent: "North America", country: "MX" },
  { code: "FM", name: "Micronesia", continent: "Oceania", country: "FM" },
  { code: "MD", name: "Moldova", continent: "Europe", country: "MD" },
  { code: "MC", name: "Monaco", continent: "Europe", country: "MC" },
  { code: "MN", name: "Mongolia", continent: "Asia", country: "MN" },
  { code: "ME", name: "Montenegro", continent: "Europe", country: "ME" },
  { code: "MA", name: "Morocco", continent: "Africa", country: "MA" },
  { code: "MZ", name: "Mozambique", continent: "Africa", country: "MZ" },
  { code: "MM", name: "Myanmar", continent: "Asia", country: "MM" },
  { code: "NA", name: "Namibia", continent: "Africa", country: "NA" },
  { code: "NR", name: "Nauru", continent: "Oceania", country: "NR" },
  { code: "NP", name: "Nepal", continent: "Asia", country: "NP" },
  { code: "NL", name: "Netherlands", continent: "Europe", country: "NL" },
  { code: "NZ", name: "New Zealand", continent: "Oceania", country: "NZ" },
  { code: "NI", name: "Nicaragua", continent: "North America", country: "NI" },
  { code: "NE", name: "Niger", continent: "Africa", country: "NE" },
  { code: "NG", name: "Nigeria", continent: "Africa", country: "NG" },
  { code: "KP", name: "North Korea", continent: "Asia", country: "KP" },
  { code: "MK", name: "North Macedonia", continent: "Europe", country: "MK" },
  { code: "NO", name: "Norway", continent: "Europe", country: "NO" },
  { code: "OM", name: "Oman", continent: "Asia", country: "OM" },
  { code: "PK", name: "Pakistan", continent: "Asia", country: "PK" },
  { code: "PW", name: "Palau", continent: "Oceania", country: "PW" },
  { code: "PS", name: "Palestine", continent: "Asia", country: "PS" },
  { code: "PA", name: "Panama", continent: "North America", country: "PA" },
  { code: "PG", name: "Papua New Guinea", continent: "Oceania", country: "PG" },
  { code: "PY", name: "Paraguay", continent: "South America", country: "PY" },
  { code: "PE", name: "Peru", continent: "South America", country: "PE" },
  { code: "PH", name: "Philippines", continent: "Asia", country: "PH" },
  { code: "PL", name: "Poland", continent: "Europe", country: "PL" },
  { code: "PT", name: "Portugal", continent: "Europe", country: "PT" },
  { code: "QA", name: "Qatar", continent: "Asia", country: "QA" },
  { code: "RO", name: "Romania", continent: "Europe", country: "RO" },
  { code: "RU", name: "Russia", continent: "Europe", country: "RU" },
  { code: "RW", name: "Rwanda", continent: "Africa", country: "RW" },
  { code: "KN", name: "Saint Kitts and Nevis", continent: "North America", country: "KN" },
  { code: "LC", name: "Saint Lucia", continent: "North America", country: "LC" },
  { code: "VC", name: "Saint Vincent and the Grenadines", continent: "North America", country: "VC" },
  { code: "WS", name: "Samoa", continent: "Oceania", country: "WS" },
  { code: "SM", name: "San Marino", continent: "Europe", country: "SM" },
  { code: "ST", name: "São Tomé and Príncipe", continent: "Africa", country: "ST" },
  { code: "SA", name: "Saudi Arabia", continent: "Asia", country: "SA" },
  { code: "SN", name: "Senegal", continent: "Africa", country: "SN" },
  { code: "RS", name: "Serbia", continent: "Europe", country: "RS" },
  { code: "SC", name: "Seychelles", continent: "Africa", country: "SC" },
  { code: "SL", name: "Sierra Leone", continent: "Africa", country: "SL" },
  { code: "SG", name: "Singapore", continent: "Asia", country: "SG" },
  { code: "SK", name: "Slovakia", continent: "Europe", country: "SK" },
  { code: "SI", name: "Slovenia", continent: "Europe", country: "SI" },
  { code: "SB", name: "Solomon Islands", continent: "Oceania", country: "SB" },
  { code: "SO", name: "Somalia", continent: "Africa", country: "SO" },
  { code: "ZA", name: "South Africa", continent: "Africa", country: "ZA" },
  { code: "KR", name: "South Korea", continent: "Asia", country: "KR" },
  { code: "SS", name: "South Sudan", continent: "Africa", country: "SS" },
  { code: "ES", name: "Spain", continent: "Europe", country: "ES" },
  { code: "LK", name: "Sri Lanka", continent: "Asia", country: "LK" },
  { code: "SD", name: "Sudan", continent: "Africa", country: "SD" },
  { code: "SR", name: "Suriname", continent: "South America", country: "SR" },
  { code: "SE", name: "Sweden", continent: "Europe", country: "SE" },
  { code: "CH", name: "Switzerland", continent: "Europe", country: "CH" },
  { code: "SY", name: "Syria", continent: "Asia", country: "SY" },
  { code: "TJ", name: "Tajikistan", continent: "Asia", country: "TJ" },
  { code: "TZ", name: "Tanzania", continent: "Africa", country: "TZ" },
  { code: "TH", name: "Thailand", continent: "Asia", country: "TH" },
  { code: "TL", name: "Timor-Leste", continent: "Asia", country: "TL" },
  { code: "TG", name: "Togo", continent: "Africa", country: "TG" },
  { code: "TO", name: "Tonga", continent: "Oceania", country: "TO" },
  { code: "TT", name: "Trinidad and Tobago", continent: "North America", country: "TT" },
  { code: "TN", name: "Tunisia", continent: "Africa", country: "TN" },
  { code: "TR", name: "Türkiye", continent: "Asia", country: "TR" },
  { code: "TM", name: "Turkmenistan", continent: "Asia", country: "TM" },
  { code: "TV", name: "Tuvalu", continent: "Oceania", country: "TV" },
  { code: "UG", name: "Uganda", continent: "Africa", country: "UG" },
  { code: "UA", name: "Ukraine", continent: "Europe", country: "UA" },
  { code: "AE", name: "United Arab Emirates", continent: "Asia", country: "AE" },
  { code: "GB", name: "United Kingdom", continent: "Europe", country: "GB" },
  { code: "US", name: "United States", continent: "North America", country: "US" },
  { code: "UY", name: "Uruguay", continent: "South America", country: "UY" },
  { code: "UZ", name: "Uzbekistan", continent: "Asia", country: "UZ" },
  { code: "VU", name: "Vanuatu", continent: "Oceania", country: "VU" },
  { code: "VA", name: "Vatican City", continent: "Europe", country: "VA" },
  { code: "VE", name: "Venezuela", continent: "South America", country: "VE" },
  { code: "VN", name: "Vietnam", continent: "Asia", country: "VN" },
  { code: "YE", name: "Yemen", continent: "Asia", country: "YE" },
  { code: "ZM", name: "Zambia", continent: "Africa", country: "ZM" },
  { code: "ZW", name: "Zimbabwe", continent: "Africa", country: "ZW" },
]

// Places outside the 195: dependent territories plus Kosovo, Taiwan and Western
// Sahara. Never counted in the stats; the ones drawn on the map can still be
// highlighted. Uninhabited ones (Antarctica, Bouvet Island…) are left out.
// prettier-ignore
export const territories: Region[] = [
  { code: "AX", name: "Åland Islands", continent: "Europe" },
  { code: "AS", name: "American Samoa", continent: "Oceania" },
  { code: "AI", name: "Anguilla", continent: "North America" },
  { code: "AW", name: "Aruba", continent: "North America" },
  { code: "BM", name: "Bermuda", continent: "North America" },
  { code: "IO", name: "British Indian Ocean Territory", continent: "Africa" },
  { code: "VG", name: "British Virgin Islands", continent: "North America" },
  { code: "BQ", name: "Caribbean Netherlands", continent: "North America" },
  { code: "KY", name: "Cayman Islands", continent: "North America" },
  { code: "CX", name: "Christmas Island", continent: "Oceania" },
  { code: "CC", name: "Cocos (Keeling) Islands", continent: "Oceania" },
  { code: "CK", name: "Cook Islands", continent: "Oceania" },
  { code: "CW", name: "Curaçao", continent: "North America" },
  { code: "FK", name: "Falkland Islands", continent: "South America", country: "FK" },
  { code: "FO", name: "Faroe Islands", continent: "Europe" },
  { code: "GF", name: "French Guiana", continent: "South America" },
  { code: "PF", name: "French Polynesia", continent: "Oceania" },
  { code: "TF", name: "French Southern and Antarctic Lands", continent: "Antarctica", country: "TF" },
  { code: "GI", name: "Gibraltar", continent: "Europe" },
  { code: "GL", name: "Greenland", continent: "North America", country: "GL" },
  { code: "GP", name: "Guadeloupe", continent: "North America" },
  { code: "GU", name: "Guam", continent: "Oceania" },
  { code: "GG", name: "Guernsey", continent: "Europe" },
  { code: "HK", name: "Hong Kong", continent: "Asia" },
  { code: "IM", name: "Isle of Man", continent: "Europe" },
  { code: "JE", name: "Jersey", continent: "Europe" },
  { code: "XK", name: "Kosovo", continent: "Europe", country: "XK" },
  { code: "MO", name: "Macau", continent: "Asia" },
  { code: "MQ", name: "Martinique", continent: "North America" },
  { code: "YT", name: "Mayotte", continent: "Africa" },
  { code: "MS", name: "Montserrat", continent: "North America" },
  { code: "NC", name: "New Caledonia", continent: "Oceania", country: "NC" },
  { code: "NU", name: "Niue", continent: "Oceania" },
  { code: "NF", name: "Norfolk Island", continent: "Oceania" },
  { code: "MP", name: "Northern Mariana Islands", continent: "Oceania" },
  { code: "PN", name: "Pitcairn Islands", continent: "Oceania" },
  { code: "PR", name: "Puerto Rico", continent: "North America", country: "PR" },
  { code: "RE", name: "Réunion", continent: "Africa" },
  { code: "BL", name: "Saint Barthélemy", continent: "North America" },
  { code: "SH", name: "Saint Helena, Ascension and Tristan da Cunha", continent: "Africa" },
  { code: "MF", name: "Saint Martin", continent: "North America" },
  { code: "PM", name: "Saint Pierre and Miquelon", continent: "North America" },
  { code: "SX", name: "Sint Maarten", continent: "North America" },
  { code: "GS", name: "South Georgia", continent: "Antarctica" },
  { code: "SJ", name: "Svalbard and Jan Mayen", continent: "Europe" },
  { code: "TW", name: "Taiwan", continent: "Asia", country: "TW" },
  { code: "TK", name: "Tokelau", continent: "Oceania" },
  { code: "TC", name: "Turks and Caicos Islands", continent: "North America" },
  { code: "VI", name: "United States Virgin Islands", continent: "North America" },
  { code: "WF", name: "Wallis and Futuna", continent: "Oceania" },
  { code: "EH", name: "Western Sahara", continent: "Africa", country: "EH" },
]
